codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: auto
        flags:
          - unit
          - integration
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto

github_checks:
  annotations: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

flags:
  unit:
    paths:
      - "app/"
      - "components/"
      - "lib/"
      - "hooks/"
      - "contexts/"
    carryforward: false
    
  integration:
    paths:
      - "__tests__/integration/"
    carryforward: false

ignore:
  - "**/*.d.ts"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/node_modules/**"
  - "e2e/**"
  - ".next/**"
  - "coverage/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "scripts/**"
  - "supabase/**"